

#ARCH=

ifeq ($(ARCH), xxxx)
CROSS_CFLAG=
CROSS_LDFLAG=
CROSS_COMPILE=
endif

CFLAG = -Wall
LDFLAG=

CC=$(CROSS_COMPILE)gcc
CFLAG +=CROSS_CFLAG
LDFLAG +=CROSS_LDFLAG

SRC  =
SRC +=


BIN1=stack_test
#BIN2=queue_test

all:$(BIN1)

$(BIN1):

